// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-ywGz86XTe8MD7riHZEzBf6Z_DiEh-cw',
    appId: '1:513426230902:web:9eb426a79e6976065b5957',
    messagingSenderId: '513426230902',
    projectId: 'latihan-firebase-7ff30',
    authDomain: 'latihan-firebase-7ff30.firebaseapp.com',
    storageBucket: 'latihan-firebase-7ff30.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3-WSxXAPQPXftHyEcJFj0mLcR4I7bv3k',
    appId: '1:513426230902:android:c54ecd19963578bc5b5957',
    messagingSenderId: '513426230902',
    projectId: 'latihan-firebase-7ff30',
    storageBucket: 'latihan-firebase-7ff30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxz_fhsPyoxsokTE7qZKYIB186juNUjJM',
    appId: '1:513426230902:ios:7ef6eb283631ac895b5957',
    messagingSenderId: '513426230902',
    projectId: 'latihan-firebase-7ff30',
    storageBucket: 'latihan-firebase-7ff30.firebasestorage.app',
    iosBundleId: 'com.ilhamzale.latihanFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxz_fhsPyoxsokTE7qZKYIB186juNUjJM',
    appId: '1:513426230902:ios:7ef6eb283631ac895b5957',
    messagingSenderId: '513426230902',
    projectId: 'latihan-firebase-7ff30',
    storageBucket: 'latihan-firebase-7ff30.firebasestorage.app',
    iosBundleId: 'com.ilhamzale.latihanFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-ywGz86XTe8MD7riHZEzBf6Z_DiEh-cw',
    appId: '1:513426230902:web:91f4bbd7f1c9cb435b5957',
    messagingSenderId: '513426230902',
    projectId: 'latihan-firebase-7ff30',
    authDomain: 'latihan-firebase-7ff30.firebaseapp.com',
    storageBucket: 'latihan-firebase-7ff30.firebasestorage.app',
  );
}
